### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'is_devrelease' since 1.2

### ISSUE THREAD

**Issue by sweh** [fanstatic/fanstatic#7]
Since version 1.2, I get the following error when starting my application that uses fanstatic.

```
  File ".appenv/2423cbf3/lib/python3.8/site-packages/fanstatic/registry.py", line 82, in make_item_from_entry_point
    if not entry_point.dist.parsed_version.is_devrelease:
AttributeError: 'Version' object has no attribute 'is_devrelease'
```

This was introduced in commit 118df73a1bcc491188c22cac9f72d8c46ab47cb1.

**Comment by icemac** [comment]
What version of ``setuptools`` are you using?

**Comment by icemac** [comment]
Are you using version 1.2 on a Python older than 3.8? (These versions are no longer supported according to the change log.)

**Comment by sweh** [comment]
> What version of `setuptools` are you using?

```
>>> setuptools.__version__
'47.1.0'
```

> Are you using version 1.2 on a Python older than 3.8? (These versions are no longer supported according to the change log.)

Nope, using Python 3.8.5.

**Comment by icemac** [comment]
Could you please try a newer setuptools version like 59.x?
